import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import {
  AlertTriangle,
  CalendarClock,
  CheckCircle2,
  ClipboardList,
  FileSearch,
  Inbox,
  RefreshCw,
  UserRound,
} from "lucide-react";
import { fetchCustomer } from "../lib/api";
import type { Customer } from "../lib/types";

interface Props {
  sessionId: string;
  customer: Customer | null;
  refreshTrigger: number;
}

interface QueueState {
  new_tickets: Array<Record<string, unknown>>;
  callbacks: Array<Record<string, unknown>>;
  escalations: Array<Record<string, unknown>>;
}

const PRIORITY_TONE: Record<string, string> = {
  urgent: "bg-red-100 text-red-700 border-red-200",
  high: "bg-amber-100 text-amber-800 border-amber-200",
  normal: "bg-slate-100 text-slate-700 border-slate-200",
  low: "bg-slate-50 text-slate-500 border-slate-200",
};

function timeAgo(iso: string | undefined): string {
  if (!iso) return "";
  try {
    const d = new Date(iso);
    const ms = Date.now() - d.getTime();
    const min = Math.floor(ms / 60000);
    if (min < 1) return "just now";
    if (min < 60) return `${min} min ago`;
    const hr = Math.floor(min / 60);
    if (hr < 24) return `${hr} hr ago`;
    return `${Math.floor(hr / 24)} d ago`;
  } catch {
    return "";
  }
}

export function AccountantView({ sessionId, customer, refreshTrigger }: Props) {
  const [state, setState] = useState<QueueState>({
    new_tickets: [],
    callbacks: [],
    escalations: [],
  });
  const [loading, setLoading] = useState(false);
  const [refreshedAt, setRefreshedAt] = useState<number | null>(null);

  const refresh = async () => {
    setLoading(true);
    try {
      const data = await fetchCustomer(sessionId);
      setState({
        new_tickets: data.new_tickets ?? [],
        callbacks: data.callbacks ?? [],
        escalations: data.escalations ?? [],
      });
      setRefreshedAt(Date.now());
    } catch {
      /* swallow */
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    refresh();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sessionId, refreshTrigger]);

  const totalItems =
    state.escalations.length + state.new_tickets.length + state.callbacks.length;

  return (
    <div className="px-4 py-6 max-w-5xl mx-auto">
      <div className="flex items-end gap-4 mb-5 flex-wrap">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-full bg-gradient-to-br from-violet-500 to-fuchsia-500 flex items-center justify-center text-white">
            <UserRound className="w-5 h-5" strokeWidth={2.2} />
          </div>
          <div>
            <div className="text-base font-semibold text-slate-900">
              {customer?.accountant_assigned ?? "Maya Torres, CPA"}
            </div>
            <div className="text-[11.5px] text-slate-500">
              Today's queue, generated by the AI agent
            </div>
          </div>
        </div>
        <div className="ml-auto flex items-center gap-2">
          <span className="text-[11px] text-slate-400">
            {refreshedAt
              ? `refreshed ${timeAgo(new Date(refreshedAt).toISOString())}`
              : "loading..."}
          </span>
          <button
            onClick={refresh}
            disabled={loading}
            className="inline-flex items-center gap-1 text-[12px] text-sky-600 hover:text-sky-800 transition disabled:opacity-50"
          >
            <RefreshCw
              className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`}
              strokeWidth={2.2}
            />
            Refresh
          </button>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-3 mb-6">
        <Stat
          label="Open escalations"
          value={state.escalations.length}
          tone="amber"
          icon={AlertTriangle}
        />
        <Stat
          label="Document tickets"
          value={state.new_tickets.length}
          tone="violet"
          icon={FileSearch}
        />
        <Stat
          label="Callbacks scheduled"
          value={state.callbacks.length}
          tone="emerald"
          icon={CalendarClock}
        />
      </div>

      {totalItems === 0 ? (
        <EmptyState />
      ) : (
        <div className="space-y-6">
          <Section
            title="Escalations needing your attention"
            icon={AlertTriangle}
            tone="amber"
            items={state.escalations}
            renderItem={(e) => (
              <EscalationCard key={String(e.id)} item={e} customer={customer} />
            )}
          />
          <Section
            title="Document tickets the agent filed"
            icon={FileSearch}
            tone="violet"
            items={state.new_tickets}
            renderItem={(t) => (
              <TicketCard key={String(t.id)} item={t} customer={customer} />
            )}
          />
          <Section
            title="Callbacks the agent booked"
            icon={CalendarClock}
            tone="emerald"
            items={state.callbacks}
            renderItem={(c) => (
              <CallbackCard key={String(c.id)} item={c} customer={customer} />
            )}
          />
        </div>
      )}
    </div>
  );
}

function Stat({
  label,
  value,
  tone,
  icon: Icon,
}: {
  label: string;
  value: number;
  tone: "amber" | "violet" | "emerald";
  icon: typeof AlertTriangle;
}) {
  const toneCls =
    tone === "amber"
      ? "from-amber-50 to-amber-100 text-amber-900 border-amber-200"
      : tone === "violet"
        ? "from-violet-50 to-violet-100 text-violet-900 border-violet-200"
        : "from-emerald-50 to-emerald-100 text-emerald-900 border-emerald-200";
  return (
    <div className={`rounded-xl border bg-gradient-to-br p-3 ${toneCls}`}>
      <div className="flex items-center gap-2 text-[11px] font-medium uppercase tracking-wide opacity-80">
        <Icon className="w-3.5 h-3.5" strokeWidth={2.2} />
        {label}
      </div>
      <div className="text-2xl font-bold tabular mt-1">{value}</div>
    </div>
  );
}

function Section({
  title,
  icon: Icon,
  tone,
  items,
  renderItem,
}: {
  title: string;
  icon: typeof AlertTriangle;
  tone: "amber" | "violet" | "emerald";
  items: Array<Record<string, unknown>>;
  renderItem: (item: Record<string, unknown>) => React.ReactNode;
}) {
  if (!items.length) return null;
  const toneCls =
    tone === "amber"
      ? "text-amber-700"
      : tone === "violet"
        ? "text-violet-700"
        : "text-emerald-700";
  return (
    <section>
      <div className="flex items-center gap-1.5 mb-2 text-[12px] font-semibold text-slate-700">
        <Icon className={`w-3.5 h-3.5 ${toneCls}`} strokeWidth={2.4} />
        {title}
        <span className="text-slate-400 font-normal">({items.length})</span>
      </div>
      <div className="space-y-2">{items.map(renderItem)}</div>
    </section>
  );
}

function EmptyState() {
  return (
    <div className="rounded-2xl border border-dashed border-slate-300 bg-white py-12 text-center">
      <Inbox
        className="w-10 h-10 text-slate-300 mx-auto mb-2"
        strokeWidth={1.6}
      />
      <div className="text-[13px] font-semibold text-slate-700">
        Inbox is clear
      </div>
      <div className="text-[12px] text-slate-500 mt-1 max-w-sm mx-auto">
        Nothing routed to you yet. Run a scenario in the Customer chat or
        WhatsApp tab and any tickets, callbacks, or escalations the agent
        creates will land here for review.
      </div>
    </div>
  );
}

function CustomerChip({ customer }: { customer: Customer | null }) {
  if (!customer) return null;
  return (
    <div className="flex items-center gap-1.5 text-[10.5px] text-slate-500">
      <div className="w-4 h-4 rounded-full bg-sky-100 text-sky-700 flex items-center justify-center font-bold text-[9px]">
        {customer.name
          .split(" ")
          .map((p) => p[0])
          .join("")
          .slice(0, 2)}
      </div>
      <span className="font-medium text-slate-700">{customer.name}</span>
      <span className="text-slate-300">&middot;</span>
      <span className="font-mono">{customer.account_id}</span>
    </div>
  );
}

function EscalationCard({
  item,
  customer,
}: {
  item: Record<string, unknown>;
  customer: Customer | null;
}) {
  const priority = String(item.priority ?? "normal");
  const priorityTone =
    PRIORITY_TONE[priority] ?? PRIORITY_TONE.normal;
  return (
    <motion.div
      initial={{ opacity: 0, y: 4 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-xl border border-slate-200 bg-white p-3.5 shadow-sm space-y-2"
    >
      <div className="flex items-center gap-2">
        <span
          className={`text-[10px] uppercase tracking-wide font-bold rounded-full px-2 py-0.5 border ${priorityTone}`}
        >
          {priority}
        </span>
        <span className="font-mono text-[11px] text-slate-500">
          {String(item.id ?? "")}
        </span>
        <span className="ml-auto text-[10.5px] text-slate-400">
          {timeAgo(String(item.created_at ?? ""))}
        </span>
      </div>
      <div className="text-[13px] text-slate-800 font-medium leading-snug">
        {String(item.reason ?? "")}
      </div>
      {Boolean(item.context) &&
        Object.keys((item.context as object) ?? {}).length > 0 && (
          <details className="text-[11px] text-slate-600">
            <summary className="cursor-pointer text-sky-600 hover:text-sky-800">
              Context the agent gathered
            </summary>
            <pre className="mt-1.5 bg-slate-50 border border-slate-100 rounded-md p-2 text-[10.5px] overflow-x-auto whitespace-pre-wrap">
              {JSON.stringify(item.context, null, 2)}
            </pre>
          </details>
        )}
      <div className="flex items-center justify-between pt-1 border-t border-slate-100">
        <CustomerChip customer={customer} />
        <div className="flex gap-1.5">
          <button className="text-[11px] text-slate-500 hover:text-slate-800 px-2 py-1 rounded-md hover:bg-slate-100 transition">
            Snooze
          </button>
          <button className="text-[11px] bg-sky-600 hover:bg-sky-700 text-white px-2.5 py-1 rounded-md transition">
            Resolve
          </button>
        </div>
      </div>
    </motion.div>
  );
}

function TicketCard({
  item,
  customer,
}: {
  item: Record<string, unknown>;
  customer: Customer | null;
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 4 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-xl border border-slate-200 bg-white p-3.5 shadow-sm space-y-2"
    >
      <div className="flex items-center gap-2">
        <FileSearch className="w-3.5 h-3.5 text-violet-500" strokeWidth={2.4} />
        <span className="font-mono text-[11px] text-slate-700 font-semibold">
          {String(item.id ?? "")}
        </span>
        <span className="text-[10px] uppercase tracking-wide text-slate-400 font-semibold">
          {String(item.doc_type ?? "")}
        </span>
        <span className="ml-auto text-[10.5px] text-slate-400">
          ETA {String(item.eta_business_days ?? "?")} biz day(s)
        </span>
      </div>
      <div className="text-[12.5px] text-slate-700 leading-snug">
        {String(item.details ?? "")}
      </div>
      <div className="flex items-center justify-between pt-1 border-t border-slate-100">
        <CustomerChip customer={customer} />
        <button className="text-[11px] inline-flex items-center gap-1 bg-violet-600 hover:bg-violet-700 text-white px-2.5 py-1 rounded-md transition">
          <CheckCircle2 className="w-3 h-3" strokeWidth={2.4} />
          Send to customer
        </button>
      </div>
    </motion.div>
  );
}

function CallbackCard({
  item,
  customer,
}: {
  item: Record<string, unknown>;
  customer: Customer | null;
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 4 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-xl border border-slate-200 bg-white p-3.5 shadow-sm space-y-2"
    >
      <div className="flex items-center gap-2">
        <CalendarClock className="w-3.5 h-3.5 text-emerald-500" strokeWidth={2.4} />
        <span className="font-mono text-[11px] text-slate-700 font-semibold">
          {String(item.id ?? "")}
        </span>
        <span className="ml-auto text-[10.5px] text-slate-400">
          {timeAgo(String(item.created_at ?? ""))}
        </span>
      </div>
      <div className="text-[12.5px] text-slate-700 leading-snug">
        <span className="font-semibold">Reason:</span>{" "}
        {String(item.reason ?? "")}
      </div>
      <div className="text-[11.5px] text-slate-500">
        <span className="font-medium text-slate-600">Preferred time:</span>{" "}
        {String(item.preferred_time ?? "not specified")}
      </div>
      <div className="flex items-center justify-between pt-1 border-t border-slate-100">
        <CustomerChip customer={customer} />
        <div className="flex items-center gap-1.5">
          <button className="text-[11px] text-slate-500 hover:text-slate-800 px-2 py-1 rounded-md hover:bg-slate-100 transition">
            Reschedule
          </button>
          <button className="text-[11px] bg-emerald-600 hover:bg-emerald-700 text-white px-2.5 py-1 rounded-md transition inline-flex items-center gap-1">
            <ClipboardList className="w-3 h-3" strokeWidth={2.4} />
            Confirm
          </button>
        </div>
      </div>
    </motion.div>
  );
}
